### ISSUE TITLE
mgm : ImportError: cannot import name 'imread' from 'scipy.misc'

### ISSUE THREAD

**Issue by anamika-yadav99** [ersilia-os/chem-sampler#4]
```
Traceback (most recent call last):
  File "generate.py", line 115, in <module>
    main(params)
  File "generate.py", line 110, in main
    params.evaluate_connected_only)
  File "/content/dl4chem-mgm/src/model/graph_generator.py", line 177, in generate_with_evaluation
    evaluate_connected_only)
  File "/content/dl4chem-mgm/src/model/graph_generator.py", line 480, in evaluate_uncond_generation
    from guacamol.assess_distribution_learning import _assess_distribution_learning
  File "/usr/local/lib/python3.7/site-packages/guacamol/assess_distribution_learning.py", line 10, in <module>
    from guacamol.benchmark_suites import distribution_learning_benchmark_suite
  File "/usr/local/lib/python3.7/site-packages/guacamol/benchmark_suites.py", line 7, in <module>
    from guacamol.standard_benchmarks import hard_cobimetinib, similarity, logP_benchmark, cns_mpo, \
  File "/usr/local/lib/python3.7/site-packages/guacamol/standard_benchmarks.py", line 6, in <module>
    from guacamol.frechet_benchmark import FrechetBenchmark
  File "/usr/local/lib/python3.7/site-packages/guacamol/frechet_benchmark.py", line 8, in <module>
    import fcd
  File "/usr/local/lib/python3.7/site-packages/fcd/__init__.py", line 1, in <module>
    from .FCD import calculate_frechet_distance, build_masked_loss, masked_accuracy, get_one_hot, myGenerator_predict, \
  File "/usr/local/lib/python3.7/site-packages/fcd/FCD.py", line 24, in <module>
    from scipy.misc import imread
ImportError: cannot import name 'imread' from 'scipy.misc' (/usr/local/lib/python3.7/site-packages/scipy/misc/__init__.py)
```

guacamol dependency updates other packages leading to this error

**Comment by GemmaTuron** [comment]
Please provide steps to reproduce this error

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron  after you build the environment from environment.yml run the following code 
```python 
from chemsampler.samplers.mgm.sampler import MgmSampler

sampler = MgmSampler()
samples = sampler.sample(n=10)
print(samples)
```

**Comment by GemmaTuron** [comment]
I'll close this issue as outdated
