### ISSUE TITLE
fast-Jtnn model issue : AttributeError: module 'rdkit' has no attribute 'RDLogger'

### ISSUE THREAD

**Issue by anamika-yadav99** [ersilia-os/chem-sampler#5]
```
Traceback (most recent call last):
  File "fast_molvae/sample.py", line 38, in <module>
    lg = rdkit.RDLogger.logger() 
AttributeError: module 'rdkit' has no attribute 'RDLogger'
Traceback (most recent call last):
  File "dummy3.py", line 16, in <module>
    samples = sampler.sample(n= 10)
  File "/home/anamika99/chem-sampler/chemsampler/samplers/fast_jtnn/sampler.py", line 29, in sample
    samples = sampler.sample(n)
  File "/home/anamika99/chem-sampler/chemsampler/tools/fast_jtnn/sampler.py", line 36, in sample
    molecules = self._read_molecules()
  File "/home/anamika99/chem-sampler/chemsampler/tools/fast_jtnn/sampler.py", line 29, in _read_molecules
    with open(self.data_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpth9joa61/data_file.txt'
```

**Comment by GemmaTuron** [comment]
Hi @anamika-yadav99 

can you please provide an update on this issue? Thanks

**Comment by GemmaTuron** [comment]
I'll close this issue as outdated
