### ISSUE TITLE
Installation issue with setup.py

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/chem-sampler#7]
Hello @anamika-yadav99 

I am at a loss as to where the requirements for chem-sampler are specified. Neither the setup.py nor the requirements.txt specifies ersilia, but when doing pip install -e . it throws back this error (on python 3.8):

  Running setup.py develop for chemsampler
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
sqlalchemy-utils 0.36.5 requires SQLAlchemy>=1.0, which is not installed.
oauth2client 4.1.3 requires rsa>=3.1.4, which is not installed.
jupyter-console 6.4.0 requires ipykernel, which is not installed.
jupyter-console 6.4.0 requires jupyter-client, which is not installed.
google-auth 2.16.0 requires cachetools<6.0,>=2.0.0, which is not installed.
google-auth 2.16.0 requires rsa<5,>=3.1.4; python_version >= "3.6", which is not installed.
botocore 1.29.46 requires jmespath<2.0.0,>=0.7.1, which is not installed.
boto3 1.26.46 requires jmespath<2.0.0,>=0.7.1, which is not installed.
bentoml 0.11.0 requires alembic, which is not installed.
bentoml 0.11.0 requires chardet, which is not installed.
bentoml 0.11.0 requires flask, which is not installed.
bentoml 0.11.0 requires grpcio, which is not installed.
bentoml 0.11.0 requires prometheus-client, which is not installed.
bentoml 0.11.0 requires psutil, which is not installed.
bentoml 0.11.0 requires sqlalchemy<1.4.0,>=1.3.0, which is not installed.
aiohttp 3.8.3 requires attrs>=17.3.0, which is not installed.
ersilia 0.1.1 requires validators, which is not installed.
bentoml 0.11.0 requires urllib3<=1.25.11, but you have urllib3 1.26.14 which is incompatible.

I can't debug this since I don't understand which setup file you are calling.

**Comment by GemmaTuron** [comment]
All this is calling old ersilia and isaura versions, and I cannot understand where are you trying to install these to change them
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bentoml 0.11.0 requires alembic, which is not installed.
bentoml 0.11.0 requires chardet, which is not installed.
bentoml 0.11.0 requires flask, which is not installed.
bentoml 0.11.0 requires grpcio, which is not installed.
bentoml 0.11.0 requires prometheus-client, which is not installed.
bentoml 0.11.0 requires psutil, which is not installed.
ersilia 0.1.1 requires validators, which is not installed.
isaura 0.17.0 requires sqlalchemy<1.4.0,>=1.3.0, but you have sqlalchemy 2.0.4 which is incompatible.
bentoml 0.11.0 requires sqlalchemy<1.4.0,>=1.3.0, but you have sqlalchemy 2.0.4 which is incompatible.
bentoml 0.11.0 requires urllib3<=1.25.11, but you have urllib3 1.26.14 which is incompatible.

**Comment by GemmaTuron** [comment]
After `pip install -e .` fails, I manually install standardiser and fpsim2 (from source, not using the fpsim2 code in the repo) and try to run the dummy.py. 
I guess some environments fail to be created, which brings to new conflicts. I need a better explanation of the conda environments management to be able to sort this out:

MollibSampler
/home/gturon/github/ersilia-os/chem-sampler/notebooks
/home/gturon/github/ersilia-os/chem-sampler/chemsampler/tools/mollib/virtual_libraries/experiments
Traceback (most recent call last):
  File "dummy.py", line 6, in <module>
    sampled_smiles = sampler.sample(smiles_list, num_samples=100, sim_ub=0.95, sim_lb=0.6, distribution="ramp")
  File "/home/gturon/github/ersilia-os/chem-sampler/chemsampler/sampler.py", line 220, in sample
    self.more(
  File "/home/gturon/github/ersilia-os/chem-sampler/chemsampler/sampler.py", line 133, in more
    sampled_smiles = self._greedy_sample(smiles_list, num_samples, time_budget_sec)
  File "/home/gturon/github/ersilia-os/chem-sampler/chemsampler/sampler.py", line 123, in _greedy_sample
    sampled_smiles.update(self._one_sampler(smiles_list))
  File "/home/gturon/github/ersilia-os/chem-sampler/chemsampler/sampler.py", line 84, in _one_sampler
    return sampler.sample(
  File "/home/gturon/github/ersilia-os/chem-sampler/chemsampler/tools/mollib/sampler.py", line 64, in sample
    self._sample(smiles_list)
  File "/home/gturon/github/ersilia-os/chem-sampler/chemsampler/tools/mollib/sampler.py", line 41, in _sample
    SimpleConda().run_commandlines(MOLLIB_CONDA_ENVIRONMENT, cmd)
  File "/home/gturon/github/ersilia-os/chem-sampler/chemsampler/utils/conda.py", line 94, in run_commandlines
    raise Exception("{0} environment does not exist".format(environment))
Exception: mollib environment does not exist

**Comment by GemmaTuron** [comment]
Updates:

In this [commit](https://github.com/ersilia-os/chem-sampler/commit/9f4ed60e709689a1fcc34e54efd1baec720a7773), I have:

- Updated requirements.txt - it now installs FPSim2 and standardiser. The error with the dependency conflicts for ersilia, bentoml and isaura persist, which I am unable to understand since we apparently do not call any of those packages here. There must be a pointer to them somewhere. @anamika-yadav99 did you inherit any code from ersilia at all? any of the models for example?
- Removed Mollib from the sampler, since mollib is only a generative package and does not have any precalculated library
- changed the filename in moler/sampler.py from moler_10k.csv to moler_100k.csv @anamika-yadav99 can you confirm this is correct?

TODO:
- Identify where is the ersilia issue happening
- Remove FPSim2 code alltogether from the repo?

**Comment by anamika-yadav99** [comment]
Hi @GemmaTuron thanks for making the changes. I have not  taken any code from Ersilia. I deleted the previous requirement.txt as well. I don't understand why this is happening. I'll ask Miquel in tomorrow's meeting and get back to you. It might be possible that he has taken some code from Ersilia.

**Comment by GemmaTuron** [comment]
I am puzzled - tried in a different system and I don't have any notifications about ersilia or isaura but still the bentoml etc issue. Leaving here the error in case its informative.
Actually the rest works fine so its not  big issue, just puzzling

  Running setup.py develop for chemsampler
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
oauth2client 4.1.3 requires httplib2>=0.9.1, which is not installed.
oauth2client 4.1.3 requires pyasn1>=0.1.7, which is not installed.
oauth2client 4.1.3 requires pyasn1-modules>=0.0.5, which is not installed.
jupyter-client 7.3.4 requires entrypoints, which is not installed.
google-auth 2.9.0 requires pyasn1-modules>=0.2.1, which is not installed.
google-auth-httplib2 0.1.0 requires httplib2>=0.15.0, which is not installed.
google-api-python-client 2.52.0 requires httplib2<1dev,>=0.15.0, which is not installed.
google-api-core 2.8.2 requires protobuf<5.0.0dev,>=3.15.0, which is not installed.
bentoml 0.11.0 requires chardet, which is not installed.
bentoml 0.11.0 requires protobuf>=3.8.0, which is not installed.
aiohttp 3.8.1 requires attrs>=17.3.0, which is not installed.
bentoml 0.11.0 requires sqlalchemy<1.4.0,>=1.3.0, but you have sqlalchemy 2.0.4 which is incompatible.
bentoml 0.11.0 requires urllib3<=1.25.11, but you have urllib3 1.26.14 which is incompatible.

**Comment by GemmaTuron** [comment]
I'll close this because this seems to be due to Ersilia installation, not the chemsampler in particular.
